Repository audacity/audacity, pull requests merged in 2023-12, with the labels that each got.

#5558 Rewrite expand cut line
  libraries/lib-wave-track/WaveClip.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  libraries/lib-wave-track/WaveTrackUtilities.cpp
  libraries/lib-wave-track/WaveTrackUtilities.h
  src/tracks/playabletrack/wavetrack/ui/CutlineHandle.cpp
Labels: Clips, refactoring

#5586 Rewrite WaveTrack pasting as interval-major
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
Labels: Clips, refactoring

#5734 Restore the working of "Tracks fit vertically zoomed" preference...
  src/ProjectAudioManager.cpp
  src/prefs/TracksPrefs.cpp
  src/prefs/TracksPrefs.h
Labels: bug, regression

#5570 5548 parse audio file title for loop metadata
  libraries/CMakeLists.txt
  libraries/lib-music-information-retrieval/.clang-format
  libraries/lib-music-information-retrieval/CMakeLists.txt
  libraries/lib-music-information-retrieval/MusicInformationRetrieval.cpp
  libraries/lib-music-information-retrieval/MusicInformationRetrieval.h
  libraries/lib-music-information-retrieval/tests/CMakeLists.txt
  libraries/lib-music-information-retrieval/tests/MusicInformationRetrievalTests.cpp
  libraries/lib-wave-track/WaveClip.cpp
  libraries/lib-wave-track/WaveClip.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  libraries/lib-wx-wrappers/AudacityDontAskAgainMessageDialog.cpp
  libraries/lib-wx-wrappers/AudacityDontAskAgainMessageDialog.h
  libraries/lib-wx-wrappers/CMakeLists.txt
  src/CMakeLists.txt
  src/ProjectFileManager.cpp
  src/menus/SelectMenus.cpp
  src/prefs/ImportExportPrefs.cpp
  src/prefs/ImportExportPrefs.h
Labels: Music

#5763 Paste bugs
  libraries/lib-wave-track/WaveTrack.cpp
Labels: Clips, refactoring

#5768 Fix clip edge drawing
  libraries/lib-wave-track/WaveTrack.h
  src/tracks/playabletrack/wavetrack/ui/SpectrumView.cpp
  src/tracks/playabletrack/wavetrack/ui/SpectrumView.h
  src/tracks/playabletrack/wavetrack/ui/WaveChannelView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveChannelView.h
  src/tracks/playabletrack/wavetrack/ui/WaveformView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveformView.h
Labels: bug, Clips

#5748 Rewrite clear and others
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
Labels: Clips, refactoring

#5807 Fix nyquist generators
  libraries/lib-wave-track/WaveTrack.cpp
Labels: bug, Clips, refactoring

#5775 Wave channel utilities
  libraries/lib-wave-track/CMakeLists.txt
  libraries/lib-wave-track/WaveChannelUtilities.cpp
  libraries/lib-wave-track/WaveChannelUtilities.h
  libraries/lib-wave-track/WaveClip.cpp
  libraries/lib-wave-track/WaveClip.h
  libraries/lib-wave-track/WaveClipUtilities.cpp
  libraries/lib-wave-track/WaveClipUtilities.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  libraries/lib-wave-track/WaveTrackUtilities.cpp
  libraries/lib-wave-track/WaveTrackUtilities.h
  src/CMakeLists.txt
  src/effects/Amplify.cpp
  src/effects/Contrast.cpp
  src/effects/Loudness.cpp
  src/effects/Normalize.cpp
  src/effects/nyquist/Nyquist.cpp
  src/menus/ClipMenus.cpp
  src/tracks/playabletrack/wavetrack/ui/SampleHandle.cpp
  src/tracks/playabletrack/wavetrack/ui/SpectrumCache.cpp
  src/tracks/playabletrack/wavetrack/ui/SpectrumCache.h
  src/tracks/playabletrack/wavetrack/ui/SpectrumView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveChannelView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveChannelView.h
  src/tracks/playabletrack/wavetrack/ui/WaveClipAdjustBorderHandle.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveClipUIUtilities.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveClipUIUtilities.h
  src/tracks/playabletrack/wavetrack/ui/WaveTrackAffordanceControls.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveformCache.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveformCache.h
  src/tracks/playabletrack/wavetrack/ui/WaveformView.cpp
  src/tracks/ui/EnvelopeHandle.cpp
Labels: Clips, refactoring

#5777 Rewrite hit tests
  libraries/lib-wave-track/WaveTrack.h
  src/prefs/SpectrogramSettings.cpp
  src/prefs/SpectrogramSettings.h
  src/prefs/WaveformSettings.cpp
  src/prefs/WaveformSettings.h
  src/tracks/playabletrack/wavetrack/ui/SampleHandle.cpp
  src/tracks/playabletrack/wavetrack/ui/SampleHandle.h
  src/tracks/playabletrack/wavetrack/ui/SpectrumView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveChannelView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveChannelView.h
  src/tracks/playabletrack/wavetrack/ui/WaveformView.cpp
  src/tracks/ui/EnvelopeHandle.cpp
  src/tracks/ui/EnvelopeHandle.h
Labels: Clips, refactoring

#5810 unsquish logo in windows installer
  win/Inno_Setup_Wizard/audacity_InnoWizardImage.bmp
Labels: non-code

#5812 Don't split source stereo track, dragging clip into another track...
  libraries/lib-wave-track/WaveTrack.cpp
Labels: bug
