Repository audacity/audacity, pull requests merged in 2023-01, with the labels that each got.

#4149 Scatter various menu items
  src/AdornedRulerPanel.cpp
  src/AudacityApp.cpp
  src/CMakeLists.txt
  src/Printing.cpp
  src/Printing.h
  src/Screenshot.cpp
  src/Screenshot.h
  src/TagsEditor.cpp
  src/TagsEditor.h
  src/TimerRecordDialog.cpp
  src/cloud/audiocom/LinkAccountDialog.cpp
  src/export/Export.cpp
  src/export/Export.h
  src/export/ExportMIDI.cpp
  src/import/ImportMIDI.cpp
  src/menus/EditMenus.cpp
  src/menus/ExtraMenus.cpp
  src/menus/FileMenus.cpp
  src/menus/HelpMenus.cpp
  src/menus/PluginMenus.cpp
  src/menus/SelectMenus.cpp
  src/menus/TransportMenus.cpp
  src/toolbars/DeviceToolBar.cpp
  src/toolbars/MeterToolBar.cpp
  src/toolbars/TranscriptionToolBar.cpp
  src/tracks/playabletrack/wavetrack/ui/SpectrumView.cpp
Labels: refactoring, menus

#4162 Fixes macOS code signing for ARM CPUs
  CMakeLists.txt
  src/CMakeLists.txt
Labels: Build / CI

#4158 Break dependency cycle
  src/AdornedRulerPanel.cpp
  src/CMakeLists.txt
  src/Menus.cpp
  src/Menus.h
  src/ProjectAudioManager.cpp
  src/commands/CommandFlag.cpp
  src/commands/CommandFlag.h
  src/menus/EditMenus.cpp
  src/menus/ExtraMenus.cpp
  src/menus/LabelMenus.cpp
  src/menus/ToolbarMenus.cpp
  src/menus/TrackMenus.cpp
  src/menus/TransportMenus.cpp
  src/toolbars/ToolBarButtons.cpp
  src/toolbars/ToolManager.cpp
  src/toolbars/ToolManager.h
  src/tracks/ui/CommonTrackPanelCell.cpp
Labels: refactoring, dependency breaking

#4199 Simplify module graph
  cmake-proxies/cmake-modules/AudacityFunctions.cmake
  cmake-proxies/cmake-modules/dependencies/wxwidgets.cmake
  libraries/lib-audio-devices/CMakeLists.txt
  libraries/lib-audio-graph/CMakeLists.txt
  libraries/lib-audio-io/CMakeLists.txt
  libraries/lib-basic-ui/CMakeLists.txt
  libraries/lib-cloud-audiocom/CMakeLists.txt
  libraries/lib-cloud-upload/CMakeLists.txt
  libraries/lib-components/CMakeLists.txt
  libraries/lib-exceptions/CMakeLists.txt
  libraries/lib-ffmpeg-support/CMakeLists.txt
  libraries/lib-files/CMakeLists.txt
  libraries/lib-math/CMakeLists.txt
  libraries/lib-module-manager/CMakeLists.txt
  libraries/lib-network-manager/CMakeLists.txt
  libraries/lib-preferences/CMakeLists.txt
  libraries/lib-project-history/CMakeLists.txt
  libraries/lib-project-rate/CMakeLists.txt
  libraries/lib-project/CMakeLists.txt
  libraries/lib-realtime-effects/CMakeLists.txt
  libraries/lib-registries/CMakeLists.txt
  libraries/lib-sample-track/CMakeLists.txt
  libraries/lib-screen-geometry/CMakeLists.txt
  libraries/lib-string-utils/CMakeLists.txt
  libraries/lib-strings/CMakeLists.txt
  libraries/lib-tags/CMakeLists.txt
  libraries/lib-theme-resources/CMakeLists.txt
  libraries/lib-theme/CMakeLists.txt
  libraries/lib-track/CMakeLists.txt
  libraries/lib-transactions/CMakeLists.txt
  libraries/lib-xml/CMakeLists.txt
  src/CMakeLists.txt
Labels: Build / CI

#4228 More module graph improvements
  cmake-proxies/cmake-modules/AudacityFunctions.cmake
  src/CMakeLists.txt
Labels: Build / CI

#4221 More in lib audio io
  libraries/lib-audio-devices/AudioIOBase.h
  libraries/lib-audio-io/AudioIO.cpp
  libraries/lib-audio-io/AudioIO.h
  libraries/lib-audio-io/ProjectAudioIO.cpp
  libraries/lib-audio-io/ProjectAudioIO.h
  src/AdornedRulerPanel.cpp
  src/BatchCommands.cpp
  src/ProjectAudioManager.cpp
  src/ProjectAudioManager.h
  src/TransportUtilities.cpp
  src/effects/EffectBase.cpp
  src/effects/EffectUI.cpp
  src/menus/TransportMenus.cpp
  src/toolbars/TranscriptionToolBar.cpp
  src/tracks/ui/Scrubbing.cpp
  src/widgets/MeterPanel.cpp
Labels: refactoring, dependency breaking

#4239 Use define_property so required CMake minimum won't increase yet
  cmake-proxies/cmake-modules/AudacityFunctions.cmake
Labels: Build / CI
