Repository audacity/audacity, pull requests merged in 2023-06, with the labels that each got.

#4738 Count tracks not channels
  libraries/lib-track-selection/SelectionState.cpp
  libraries/lib-track/Track.cpp
  libraries/lib-track/Track.h
  src/commands/ScreenshotCommand.cpp
  src/effects/EffectUI.cpp
  src/import/ImportAUP.cpp
  src/menus/LabelMenus.cpp
  src/menus/TrackMenus.cpp
  src/toolbars/TranscriptionToolBar.cpp
  src/tracks/labeltrack/ui/LabelTrackView.cpp
Labels: refactoring

#4712 fix broken links, remove wikilinks
  CONTRIBUTING.md
  INSTALL
  PULL_REQUEST_TEMPLATE.md
  README.md
  libraries/lib-wx-init/HelpText.cpp
  win/Inno_Setup_Wizard/audacity_InnoWizard_InfoBefore.rtf.in
Labels: non-code

#4623 Namespace composite
  libraries/lib-utility/CMakeLists.txt
  libraries/lib-utility/Composite.cpp
  libraries/lib-utility/Composite.h
  libraries/lib-utility/tests/CMakeLists.txt
  libraries/lib-utility/tests/CompositeTest.cpp
Labels: template<> meta::poetry

#4743 Fixes the audio.com upload flow
  libraries/lib-cloud-audiocom/ServiceConfig.cpp
  libraries/lib-cloud-audiocom/ServiceConfig.h
  libraries/lib-cloud-audiocom/UploadService.cpp
  libraries/lib-cloud-audiocom/UploadService.h
  src/cloud/audiocom/ShareAudioDialog.cpp
  src/cloud/audiocom/ShareAudioDialog.h
Labels: audio sharing

#4759 Remove mono track types
  libraries/lib-audio-graph/AudioGraphChannel.cpp
  libraries/lib-audio-graph/AudioGraphChannel.h
  libraries/lib-audio-graph/CMakeLists.txt
  libraries/lib-audio-io/AudioIO.cpp
  libraries/lib-effects/MixAndRender.cpp
  libraries/lib-effects/PerTrackEffect.cpp
  libraries/lib-effects/PerTrackEffect.h
  libraries/lib-sample-track/CMakeLists.txt
  libraries/lib-sample-track/EffectStage.cpp
  libraries/lib-sample-track/EffectStage.h
  libraries/lib-sample-track/Mix.cpp
  libraries/lib-sample-track/Mix.h
  libraries/lib-sample-track/SampleTrack.cpp
  libraries/lib-sample-track/SampleTrack.h
  libraries/lib-track/Track.cpp
  libraries/lib-track/Track.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  src/cloud/audiocom/ShareAudioDialog.cpp
  src/effects/Loudness.cpp
  src/effects/SimpleMono.cpp
  src/effects/SimpleMono.h
  src/effects/TwoPassSimpleMono.cpp
  src/effects/TwoPassSimpleMono.h
  src/export/Export.cpp
  src/export/ExportMultiple.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveTrackControls.cpp
Labels: refactoring, Tracks

#4742 Wide wave clip
  libraries/lib-math/SampleFormat.h
  libraries/lib-project-file-io/SqliteSampleBlock.cpp
  libraries/lib-wave-track/SampleBlock.h
  libraries/lib-wave-track/Sequence.cpp
  libraries/lib-wave-track/Sequence.h
  libraries/lib-wave-track/WaveClip.cpp
  libraries/lib-wave-track/WaveClip.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  src/Benchmark.cpp
  src/import/ImportAUP.cpp
  src/menus/EditMenus.cpp
  src/tracks/playabletrack/wavetrack/ui/GetWaveDisplay.cpp
  src/tracks/playabletrack/wavetrack/ui/GetWaveDisplay.h
  src/tracks/playabletrack/wavetrack/ui/SpectrumCache.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveTrackControls.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveTrackShifter.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveTrackView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveTrackView.h
  src/tracks/playabletrack/wavetrack/ui/WaveformCache.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveformCache.h
  src/tracks/playabletrack/wavetrack/ui/WaveformView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveformView.h
Labels: refactoring

#4795 Audio io does not use track
  libraries/lib-audio-io/AudioIO.cpp
  libraries/lib-audio-io/AudioIO.h
  libraries/lib-audio-io/AudioIOExt.h
  libraries/lib-audio-io/AudioIOListener.cpp
  libraries/lib-audio-io/AudioIOListener.h
  libraries/lib-audio-io/CMakeLists.txt
  libraries/lib-audio-io/PlaybackSchedule.cpp
  libraries/lib-audio-io/PlaybackSchedule.h
  libraries/lib-audio-io/RingBuffer.cpp
  libraries/lib-audio-io/RingBuffer.h
  libraries/lib-mixer/AudioIOSequences.cpp
  libraries/lib-mixer/AudioIOSequences.h
  libraries/lib-mixer/CMakeLists.txt
  libraries/lib-mixer/WideSampleSequence.h
  libraries/lib-realtime-effects/CMakeLists.txt
  libraries/lib-realtime-effects/RealtimeEffectList.cpp
  libraries/lib-realtime-effects/RealtimeEffectList.h
  libraries/lib-realtime-effects/RealtimeEffectManager.cpp
  libraries/lib-realtime-effects/RealtimeEffectManager.h
  libraries/lib-realtime-effects/RealtimeEffectState.cpp
  libraries/lib-realtime-effects/RealtimeEffectState.h
  libraries/lib-sample-track/SampleTrack.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  src/DefaultPlaybackPolicy.cpp
  src/MIDIPlay.cpp
  src/MIDIPlay.h
  src/NoteTrack.h
  src/ProjectAudioManager.cpp
  src/ProjectAudioManager.h
  src/RealtimeEffectPanel.cpp
  src/RealtimeEffectPanel.h
  src/ScrubState.cpp
  src/TrackPanel.cpp
  src/TransportUtilities.cpp
  src/TransportUtilities.h
  src/menus/PluginMenus.cpp
  src/menus/TransportMenus.cpp
  src/tracks/playabletrack/ui/PlayableTrackButtonHandles.cpp
Labels: refactoring, Beats & Measures

#4823 Fix bug dragging a clip into a track with a different rate
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
Labels: Clips

#4650 Rewrite track type switch
  libraries/lib-effects/PerTrackEffect.cpp
  libraries/lib-project-file-io/ProjectFileIO.cpp
  libraries/lib-time-track/TimeTrack.cpp
  libraries/lib-track/Track.h
  libraries/lib-utility/CMakeLists.txt
  libraries/lib-utility/Callable.h
  libraries/lib-utility/TypeList.cpp
  libraries/lib-utility/TypeList.h
  libraries/lib-utility/TypeSwitch.cpp
  libraries/lib-utility/TypeSwitch.h
  libraries/lib-utility/tests/CallableTest.cpp
  libraries/lib-wave-track/WaveTrack.cpp
  src/LabelTrack.cpp
  src/NoteTrack.cpp
  src/ProjectFileManager.cpp
  src/commands/GetInfoCommand.cpp
  src/commands/SetClipCommand.cpp
  src/commands/SetEnvelopeCommand.cpp
  src/effects/AutoDuck.cpp
  src/effects/ChangeSpeed.cpp
  src/effects/Generator.cpp
  src/effects/Paulstretch.cpp
  src/effects/Repeat.cpp
  src/effects/Reverse.cpp
  src/effects/SBSMSEffect.cpp
  src/effects/SoundTouchEffect.cpp
  src/effects/TruncSilence.cpp
  src/effects/nyquist/Nyquist.cpp
  src/menus/EditMenus.cpp
  src/menus/LabelMenus.cpp
  src/menus/TrackMenus.cpp
  src/tracks/playabletrack/notetrack/ui/StretchHandle.cpp
  src/tracks/ui/BrushHandle.cpp
  src/tracks/ui/EnvelopeHandle.cpp
  src/tracks/ui/SelectHandle.cpp
Labels: code quality, template<> meta::poetry
