Repository audacity/audacity, pull requests merged in 2023-04, with the labels that each got.

#4416 "Delay" effect: Add better quality pitch shifting
  plug-ins/delay.ny
Labels: plugins, Effects

#4484 Disable 18.04 builds. Use 22.04 instead
  .github/workflows/build.yml
Labels: Build / CI

#4535 Variant utilities
  libraries/lib-module-manager/PluginManager.cpp
  libraries/lib-utility/CMakeLists.txt
  libraries/lib-utility/MemoryX.h
  libraries/lib-utility/Variant.h
  libraries/lib-utility/tests/CMakeLists.txt
  libraries/lib-utility/tests/VariantTest.cpp
Labels: code quality

#4359 Extract lib vst
  libraries/CMakeLists.txt
  libraries/lib-utility/CFResources.cpp
  libraries/lib-utility/CFResources.h
  libraries/lib-utility/CMakeLists.txt
  libraries/lib-vst/CMakeLists.txt
  libraries/lib-vst/VSTEffectBase.cpp
  libraries/lib-vst/VSTEffectBase.h
  libraries/lib-vst/VSTEffectsModule.cpp
  libraries/lib-vst/VSTEffectsModule.h
  libraries/lib-vst/VSTInstance.cpp
  libraries/lib-vst/VSTInstance.h
  libraries/lib-vst/VSTWrapper.cpp
  libraries/lib-vst/VSTWrapper.h
  libraries/lib-vst/aeffectx.h
  src/CMakeLists.txt
  src/effects/VST/VSTControl.h
  src/effects/VST/VSTControlGTK.cpp
  src/effects/VST/VSTControlGTK.h
  src/effects/VST/VSTControlMSW.cpp
  src/effects/VST/VSTControlMSW.h
  src/effects/VST/VSTControlOSX.h
  src/effects/VST/VSTControlOSX.mm
  src/effects/VST/VSTEditor.cpp
  src/effects/VST/VSTEditor.h
  src/effects/VST/VSTEffect.cpp
  src/effects/VST/VSTEffect.h
  src/effects/VST/VSTEffectOptionsDialog.cpp
  src/effects/VST/VSTEffectOptionsDialog.h
Labels: Effects, refactoring, libraries

#4400 Extract lib lv2
  libraries/CMakeLists.txt
  libraries/lib-lv2/CMakeLists.txt
  libraries/lib-lv2/LV2EffectBase.cpp
  libraries/lib-lv2/LV2EffectBase.h
  libraries/lib-lv2/LV2FeaturesList.cpp
  libraries/lib-lv2/LV2FeaturesList.h
  libraries/lib-lv2/LV2Instance.cpp
  libraries/lib-lv2/LV2Instance.h
  libraries/lib-lv2/LV2InstanceFeaturesList.cpp
  libraries/lib-lv2/LV2InstanceFeaturesList.h
  libraries/lib-lv2/LV2Ports.cpp
  libraries/lib-lv2/LV2Ports.h
  libraries/lib-lv2/LV2Preferences.cpp
  libraries/lib-lv2/LV2Preferences.h
  libraries/lib-lv2/LV2Symbols.cpp
  libraries/lib-lv2/LV2Symbols.h
  libraries/lib-lv2/LV2Utils.h
  libraries/lib-lv2/LV2Wrapper.cpp
  libraries/lib-lv2/LV2Wrapper.h
  libraries/lib-lv2/LoadLV2.cpp
  libraries/lib-lv2/LoadLV2.h
  libraries/lib-lv2/lv2_external_ui.h
  libraries/lib-lv2/zix/common.h
  libraries/lib-lv2/zix/ring.cpp
  libraries/lib-lv2/zix/ring.h
  src/CMakeLists.txt
  src/effects/lv2/LV2Editor.cpp
  src/effects/lv2/LV2Editor.h
  src/effects/lv2/LV2Effect.cpp
  src/effects/lv2/LV2Effect.h
  src/effects/lv2/LV2PreferencesDialog.cpp
  src/effects/lv2/LV2PreferencesDialog.h
  src/effects/lv2/LV2UIFeaturesList.cpp
  src/effects/lv2/LV2UIFeaturesList.h
Labels: Effects, refactoring, libraries

#4337 Extract lib ladspa
  CMakeLists.txt
  libraries/CMakeLists.txt
  libraries/lib-ladspa/CMakeLists.txt
  libraries/lib-ladspa/LadspaEffectBase.cpp
  libraries/lib-ladspa/LadspaEffectBase.h
  libraries/lib-ladspa/LadspaEffectsModule.cpp
  libraries/lib-ladspa/LadspaEffectsModule.h
  libraries/lib-ladspa/LadspaInstance.cpp
  libraries/lib-ladspa/LadspaInstance.h
  libraries/lib-ladspa/ladspa.h
  src/CMakeLists.txt
  src/effects/ladspa/LadspaEditor.cpp
  src/effects/ladspa/LadspaEditor.h
  src/effects/ladspa/LadspaEffect.cpp
  src/effects/ladspa/LadspaEffect.h
  src/effects/ladspa/LadspaEffectOptionsDialog.cpp
  src/effects/ladspa/LadspaEffectOptionsDialog.h
Labels: Effects, refactoring, libraries

#4579 GCC13 support
  lib-src/libnyquist/nyquist/nyqstk/include/Stk.h
  libraries/lib-effects/LoadEffects.cpp
  libraries/lib-module-manager/PluginHost.cpp
Labels: Build / CI

#4572 Namespace callable
  libraries/lib-ladspa/LadspaEffectsModule.h
  libraries/lib-lv2/LV2InstanceFeaturesList.h
  libraries/lib-lv2/LoadLV2.h
  libraries/lib-numeric-formats/NumericConverterRegistry.cpp
  libraries/lib-numeric-formats/NumericConverterRegistry.h
  libraries/lib-utility/CMakeLists.txt
  libraries/lib-utility/Callable.cpp
  libraries/lib-utility/Callable.h
  libraries/lib-utility/GlobalVariable.h
  libraries/lib-utility/Variant.cpp
  libraries/lib-utility/Variant.h
  libraries/lib-utility/tests/CMakeLists.txt
  libraries/lib-utility/tests/CallableTest.cpp
  libraries/lib-utility/tests/VariantTest.cpp
  libraries/lib-vst/VSTEffectsModule.h
  libraries/lib-vst3/VST3EffectsModule.h
  src/commands/CommandManager.h
  src/menus/MenuHelper.cpp
Labels: code quality, template<> meta::poetry

#4338 Extract lib audiounit
  CMakeLists.txt
  libraries/CMakeLists.txt
  libraries/lib-audio-unit/AudioUnitEffectBase.cpp
  libraries/lib-audio-unit/AudioUnitEffectBase.h
  libraries/lib-audio-unit/AudioUnitEffectsModule.cpp
  libraries/lib-audio-unit/AudioUnitEffectsModule.h
  libraries/lib-audio-unit/AudioUnitInstance.cpp
  libraries/lib-audio-unit/AudioUnitInstance.h
  libraries/lib-audio-unit/AudioUnitUtils.cpp
  libraries/lib-audio-unit/AudioUnitUtils.h
  libraries/lib-audio-unit/AudioUnitWrapper.cpp
  libraries/lib-audio-unit/AudioUnitWrapper.h
  libraries/lib-audio-unit/CMakeLists.txt
  src/CMakeLists.txt
  src/effects/audiounits/AudioUnitEffect.cpp
  src/effects/audiounits/AudioUnitEffect.h
  src/effects/audiounits/AudioUnitEffectOptionsDialog.cpp
  src/effects/audiounits/AudioUnitEffectOptionsDialog.h
Labels: Effects, refactoring, libraries

#4581 Namespace type enumerator
  libraries/lib-track/Track.h
  libraries/lib-utility/CMakeLists.txt
  libraries/lib-utility/TypeEnumerator.cpp
  libraries/lib-utility/TypeEnumerator.h
  libraries/lib-utility/tests/CMakeLists.txt
  libraries/lib-utility/tests/TypeEnumeratorTest.cpp
Labels: code quality, template<> meta::poetry

#4551 Anonymous items
  libraries/lib-numeric-formats/NumericConverterRegistry.cpp
  libraries/lib-numeric-formats/NumericConverterRegistry.h
  libraries/lib-registries/Registry.cpp
  libraries/lib-registries/Registry.h
  libraries/lib-snapping/SnapUtils.cpp
  libraries/lib-snapping/SnapUtils.h
  src/BatchProcessDialog.cpp
  src/Menus.cpp
  src/Printing.cpp
  src/RealtimeEffectPanel.cpp
  src/commands/CommandManager.h
  src/export/Export.cpp
  src/export/Export.h
  src/import/Import.cpp
  src/import/Import.h
  src/menus/ClipMenus.cpp
  src/menus/EditMenus.cpp
  src/menus/ExtraMenus.cpp
  src/menus/FileMenus.cpp
  src/menus/HelpMenus.cpp
  src/menus/LabelMenus.cpp
  src/menus/NavigationMenus.cpp
  src/menus/PluginMenus.cpp
  src/menus/SelectMenus.cpp
  src/menus/TimelineMenus.cpp
  src/menus/ToolbarMenus.cpp
  src/menus/TrackMenus.cpp
  src/menus/TransportMenus.cpp
  src/menus/ViewMenus.cpp
  src/prefs/LibraryPrefs.cpp
  src/prefs/LibraryPrefs.h
  src/prefs/PrefsPanel.cpp
  src/prefs/PrefsPanel.h
  src/toolbars/DeviceToolBar.cpp
  src/toolbars/MeterToolBar.cpp
  src/toolbars/SnappingToolBar.cpp
  src/toolbars/ToolsToolBar.cpp
  src/toolbars/TranscriptionToolBar.cpp
  src/tracks/playabletrack/wavetrack/ui/SpectrumView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveformView.cpp
  src/tracks/ui/Scrubbing.cpp
  src/widgets/PopupMenuTable.cpp
  src/widgets/PopupMenuTable.h
Labels: code quality

#4588 Effect preview progress
  libraries/lib-wx-init/ProgressDialog.cpp
  src/effects/EffectUI.cpp
  src/effects/EffectUI.h
Labels: Effects

#4593 New namespace Tuple in lib-utility...
  libraries/lib-utility/CMakeLists.txt
  libraries/lib-utility/Tuple.cpp
  libraries/lib-utility/Tuple.h
  libraries/lib-utility/tests/CMakeLists.txt
  libraries/lib-utility/tests/TupleTest.cpp
Labels: template<> meta::poetry
