Repository audacity/audacity, pull requests merged in 2023-10, with the labels that each got.

#5324 5313 clean up all hidden data when rendering stretch
  libraries/lib-wave-track/WaveClip.cpp
Labels: time-stretching

#5320 Don't compute interpolation of samples when no pitch shifting
  libraries/lib-time-and-pitch/StaffPad/TimeAndPitch.cpp
Labels: performance

#5341 5231 fix error msg when dragging pencil beyond right boundary
  libraries/lib-screen-geometry/ZoomInfo.cpp
  libraries/lib-screen-geometry/ZoomInfo.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  src/tracks/playabletrack/wavetrack/ui/SampleHandle.cpp
  src/tracks/playabletrack/wavetrack/ui/SampleHandle.h
  src/tracks/playabletrack/wavetrack/ui/WaveformView.cpp
Labels: Beats & Measures, time-stretching

#5350 Do not commit output of nyquist analyzers
  libraries/lib-effects/EffectOutputTracks.cpp
  libraries/lib-effects/EffectOutputTracks.h
  libraries/lib-effects/PerTrackEffect.cpp
  src/effects/AutoDuck.cpp
  src/effects/ChangeSpeed.cpp
  src/effects/ClickRemoval.cpp
  src/effects/Equalization.cpp
  src/effects/FindClipping.cpp
  src/effects/Generator.cpp
  src/effects/Loudness.cpp
  src/effects/NoiseReduction.cpp
  src/effects/Normalize.cpp
  src/effects/Paulstretch.cpp
  src/effects/Repair.cpp
  src/effects/Repeat.cpp
  src/effects/Reverse.cpp
  src/effects/SBSMSEffect.cpp
  src/effects/SoundTouchEffect.cpp
  src/effects/StereoToMono.cpp
  src/effects/TruncSilence.cpp
  src/effects/TwoPassSimpleMono.cpp
  src/effects/nyquist/Nyquist.cpp
Labels: time-stretching

#5308 Avoid frequent allocation of little vectors of pointers in stretch
  libraries/lib-stretching-sequence/AudioSegment.h
  libraries/lib-stretching-sequence/ClipSegment.cpp
  libraries/lib-stretching-sequence/ClipSegment.h
  libraries/lib-stretching-sequence/SilenceSegment.cpp
  libraries/lib-stretching-sequence/SilenceSegment.h
  libraries/lib-stretching-sequence/StretchingSequence.cpp
  libraries/lib-stretching-sequence/tests/ClipSegmentTest.cpp
  libraries/lib-stretching-sequence/tests/MockAudioSegmentFactory.h
  libraries/lib-stretching-sequence/tests/SilenceSegmentTest.cpp
  libraries/lib-time-and-pitch/StaffPadTimeAndPitch.cpp
Labels: performance

#5400 5397 fix sbsms integration
  libraries/lib-effects/Effect.cpp
  libraries/lib-effects/Effect.h
  src/effects/SBSMSEffect.cpp
  src/effects/SBSMSEffect.h
Labels: bug, time-stretching

#4684 More registry type checking
  libraries/lib-import-export/ExportPluginRegistry.cpp
  libraries/lib-import-export/Import.cpp
  libraries/lib-numeric-formats/NumericConverterRegistry.cpp
  libraries/lib-registries/Registry.cpp
  libraries/lib-registries/Registry.h
  libraries/lib-snapping/SnapUtils.cpp
  libraries/lib-snapping/SnapUtils.h
  libraries/lib-utility/Tuple.h
  libraries/lib-utility/tests/TupleTest.cpp
  src/Menus.cpp
  src/Menus.h
  src/RealtimeEffectPanel.cpp
  src/commands/CommandManager.h
  src/menus/HelpMenus.cpp
  src/menus/MenuHelper.h
  src/prefs/LibraryPrefs.cpp
  src/prefs/PrefsPanel.cpp
  src/toolbars/SnappingToolBar.cpp
  src/widgets/PopupMenuTable.cpp
  src/widgets/PopupMenuTable.h
Labels: code quality
