Repository audacity/audacity, pull requests merged in 2023-09, with the labels that each got.

#5134 Bugfix: Wrong display of time when punch and roll recording on an expanded clip
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  src/ProjectAudioManager.cpp
Labels: Beats & Measures, time-stretching

#5031 Waveform view rewrites
  libraries/lib-stretching-sequence/ClipInterface.cpp
  libraries/lib-stretching-sequence/ClipInterface.h
  libraries/lib-stretching-sequence/tests/FloatVectorClip.cpp
  libraries/lib-stretching-sequence/tests/FloatVectorClip.h
  libraries/lib-wave-track/WaveClip.cpp
  libraries/lib-wave-track/WaveClip.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  libraries/lib-wave-track/WideClip.cpp
  libraries/lib-wave-track/WideClip.h
  src/ProjectFileManager.cpp
  src/TrackPanel.cpp
  src/commands/SetClipCommand.cpp
  src/commands/SetClipCommand.h
  src/commands/SetTrackInfoCommand.cpp
  src/commands/SetTrackInfoCommand.h
  src/effects/Repeat.cpp
  src/tracks/playabletrack/wavetrack/WaveTrackUtils.h
  src/tracks/playabletrack/wavetrack/ui/SpectrumCache.cpp
  src/tracks/playabletrack/wavetrack/ui/SpectrumCache.h
  src/tracks/playabletrack/wavetrack/ui/SpectrumView.cpp
  src/tracks/playabletrack/wavetrack/ui/SpectrumView.h
  src/tracks/playabletrack/wavetrack/ui/WaveChannelView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveChannelView.h
  src/tracks/playabletrack/wavetrack/ui/WaveTrackAffordanceControls.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveformCache.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveformCache.h
  src/tracks/playabletrack/wavetrack/ui/WaveformView.cpp
Labels: refactoring, Beats & Measures

#5128 Rewrite cutline editing
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  src/WaveTrackLocation.cpp
  src/WaveTrackLocation.h
  src/tracks/playabletrack/wavetrack/ui/CutlineHandle.cpp
  src/tracks/playabletrack/wavetrack/ui/CutlineHandle.h
  src/tracks/playabletrack/wavetrack/ui/SpectrumView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveChannelView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveformView.cpp
Labels: refactoring, time-stretching

#5130 Deduplicate effect stack
  libraries/lib-audio-io/AudioIO.cpp
  libraries/lib-audio-io/AudioIO.h
  libraries/lib-audio-io/CMakeLists.txt
  libraries/lib-channel/Channel.cpp
  libraries/lib-channel/Channel.h
  libraries/lib-mixer/AudioIOSequences.h
  libraries/lib-mixer/CMakeLists.txt
  libraries/lib-mixer/WideSampleSequence.cpp
  libraries/lib-mixer/WideSampleSequence.h
  libraries/lib-playable-track/PlayableTrack.cpp
  libraries/lib-realtime-effects/CMakeLists.txt
  libraries/lib-realtime-effects/RealtimeEffectList.cpp
  libraries/lib-realtime-effects/RealtimeEffectList.h
  libraries/lib-realtime-effects/RealtimeEffectManager.cpp
  libraries/lib-realtime-effects/RealtimeEffectManager.h
  libraries/lib-realtime-effects/RealtimeEffectState.cpp
  libraries/lib-realtime-effects/RealtimeEffectState.h
  libraries/lib-sample-track/SampleTrack.cpp
  libraries/lib-sample-track/SampleTrack.h
  libraries/lib-stretching-sequence/StretchingSequence.cpp
  libraries/lib-stretching-sequence/StretchingSequence.h
  libraries/lib-stretching-sequence/tests/MockPlayableSequence.h
  libraries/lib-track/Track.cpp
  libraries/lib-track/Track.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  src/ProjectAudioManager.cpp
  src/TrackPanel.cpp
  src/prefs/SpectrogramSettings.cpp
  src/prefs/WaveformSettings.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveChannelView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveTrackControls.cpp
Labels: refactoring, time-stretching

#5172 Fix Punch and Roll recording with overdub
  src/ProjectAudioManager.cpp
Labels: recording

#5138 Destructive effects applied to stretched clips
  libraries/lib-effects/EffectOutputTracks.cpp
  libraries/lib-effects/EffectOutputTracks.h
  libraries/lib-effects/PerTrackEffect.cpp
  libraries/lib-math/SampleCount.cpp
  libraries/lib-mixer/WideSampleSequence.cpp
  libraries/lib-mixer/WideSampleSequence.h
  libraries/lib-track/Track.h
  libraries/lib-wave-track/CMakeLists.txt
  libraries/lib-wave-track/WaveClip.cpp
  libraries/lib-wave-track/WaveClip.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  libraries/lib-wave-track/WaveTrackSink.cpp
  libraries/lib-wave-track/WaveTrackSink.h
  libraries/lib-wave-track/WaveTrackUtilities.cpp
  libraries/lib-wave-track/WaveTrackUtilities.h
  src/ProjectAudioManager.cpp
  src/effects/AutoDuck.cpp
  src/effects/AutoDuck.h
  src/effects/ChangeSpeed.cpp
  src/effects/ClickRemoval.cpp
  src/effects/Equalization.cpp
  src/effects/Generator.cpp
  src/effects/Loudness.cpp
  src/effects/Loudness.h
  src/effects/NoiseReduction.cpp
  src/effects/NoiseRemoval.cpp
  src/effects/Normalize.cpp
  src/effects/Paulstretch.cpp
  src/effects/Repair.cpp
  src/effects/Repeat.cpp
  src/effects/Reverse.cpp
  src/effects/SBSMSEffect.cpp
  src/effects/SoundTouchEffect.cpp
  src/effects/StereoToMono.cpp
  src/effects/TruncSilence.cpp
  src/effects/TwoPassSimpleMono.cpp
  src/effects/nyquist/Nyquist.cpp
  src/menus/EditMenus.cpp
  src/tracks/playabletrack/wavetrack/ui/CutlineHandle.cpp
  src/tracks/playabletrack/wavetrack/ui/SampleHandle.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveformView.cpp
Labels: time-stretching

#5139 Repair plot spectrum command for stretched data
  src/FreqWindow.cpp
  src/FreqWindow.h
Labels: Beats & Measures, time-stretching

#5201 3.3.3 and older versions cannot open project files with any stretches
  libraries/lib-wave-track/WaveTrack.cpp
Labels: time-stretching

#5182 Fix silence audio command
  libraries/lib-time-track/TimeTrack.cpp
  libraries/lib-time-track/TimeTrack.h
  libraries/lib-track/Track.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  src/LabelTrack.cpp
  src/LabelTrack.h
  src/NoteTrack.cpp
  src/NoteTrack.h
  src/menus/EditMenus.cpp
  src/menus/LabelMenus.cpp
Labels: Beats & Measures, time-stretching

#5212 Remove TrackList::Channels in ImportAUP.cpp...
  modules/mod-aup/ImportAUP.cpp
Labels: refactoring

#5228 Fix writing to atomics in ShareAudioDialog.cpp
  src/cloud/audiocom/ShareAudioDialog.cpp
Labels: bug

#5220 Applying effect on stretched clip renders only the selected region
  libraries/lib-wave-track/WaveClip.cpp
Labels: Beats & Measures, time-stretching

#5042 Time stretching 3 of 6 repair drawing tools for stretched audio
  libraries/lib-wave-track/WaveClip.cpp
  libraries/lib-wave-track/WaveClip.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  src/tracks/playabletrack/wavetrack/ui/SampleHandle.cpp
  src/tracks/playabletrack/wavetrack/ui/SampleHandle.h
Labels: Beats & Measures

#5233 Fix reads of uninitialized data in lib-time-and-pitch...
  libraries/lib-time-and-pitch/StaffPad/TimeAndPitch.cpp
Labels: time-stretching

#5175 Deterministic zero-fill whenever WaveTrack::Get[Floats] fails...
  libraries/lib-mixer/MixerSource.cpp
  libraries/lib-mixer/WideSampleSequence.cpp
  libraries/lib-mixer/WideSampleSequence.h
  libraries/lib-stretching-sequence/StretchingSequence.cpp
  libraries/lib-stretching-sequence/StretchingSequence.h
  libraries/lib-stretching-sequence/tests/MockPlayableSequence.h
  libraries/lib-stretching-sequence/tests/StretchingSequenceIntegrationTest.cpp
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  src/Benchmark.cpp
Labels: time-stretching

#5245 Wrong tempo fix
  src/ProjectTimeRuler.cpp
  src/widgets/BeatsFormat.cpp
  src/widgets/BeatsFormat.h
Labels: bug, regression, Beats & Measures

#5250 5124 improve time stretching quality for high sample rates
  libraries/lib-stretching-sequence/ClipSegment.cpp
  libraries/lib-time-and-pitch/StaffPad/TimeAndPitch.cpp
  libraries/lib-time-and-pitch/StaffPad/TimeAndPitch.h
  libraries/lib-time-and-pitch/StaffPadTimeAndPitch.cpp
  libraries/lib-time-and-pitch/StaffPadTimeAndPitch.h
  libraries/lib-time-and-pitch/tests/StaffPadTimeAndPitchTest.cpp
  libraries/lib-wave-track/WaveClip.cpp
Labels: Beats & Measures, time-stretching
