Repository audacity/audacity, pull requests merged in 2023-11, with the labels that each got.

#5458 Bugfix: silence audio does not delete clips
  libraries/lib-wave-track/WaveTrack.cpp
Labels: P1

#5552 Fixes GTK detection when using system wxWidgets
  cmake-proxies/cmake-modules/dependencies/wxwidgets.cmake
Labels: Build / CI

#5551 Nyquist: do not assume that a track is selected
  src/effects/nyquist/Nyquist.cpp
Labels: regression

#5443 Toolkit neutral command manager
  libraries/lib-basic-ui/BasicUI.h
  libraries/lib-menus/CMakeLists.txt
  libraries/lib-menus/CommandManager.cpp
  libraries/lib-menus/CommandManager.h
  libraries/lib-wx-init/wxWidgetsBasicUI.cpp
  libraries/lib-wx-init/wxWidgetsBasicUI.h
  modules/mod-nyq-bench/NyqBench.h
  src/BatchCommands.cpp
  src/BatchProcessDialog.cpp
  src/CMakeLists.txt
  src/FreqWindow.cpp
  src/MenuCreator.cpp
  src/MenuCreator.h
  src/ProjectAudioManager.cpp
  src/ProjectWindow.cpp
  src/Screenshot.cpp
  src/SelectUtilities.cpp
  src/SpectralDataDialog.cpp
  src/commands/ScreenshotCommand.cpp
  src/effects/Contrast.cpp
  src/effects/EffectUI.cpp
  src/menus/EditMenus.cpp
  src/menus/PluginMenus.cpp
  src/menus/TimelineMenus.cpp
  src/menus/ViewMenus.cpp
  src/prefs/PrefsDialog.cpp
  src/toolbars/CutCopyPasteToolBar.cpp
  src/toolbars/EditToolBar.cpp
  src/toolbars/ToolBar.cpp
  src/toolbars/ToolBarButtons.cpp
  src/toolbars/ToolManager.cpp
  src/tracks/playabletrack/ui/PlayableTrackButtonHandles.cpp
  src/tracks/ui/CommonTrackControls.cpp
  src/tracks/ui/CommonTrackPanelCell.cpp
  src/tracks/ui/Scrubbing.cpp
  src/tracks/ui/SelectHandle.cpp
  src/tracks/ui/TrackButtonHandles.cpp
  src/widgets/KeyView.cpp
  src/widgets/PopupMenuTable.h
Labels: refactoring, libraries & modules

#5393 Pending track nonsense
  libraries/lib-project-file-io/ProjectFileIO.cpp
  libraries/lib-project-file-io/SqliteSampleBlock.cpp
  libraries/lib-track-selection/SyncLock.cpp
  libraries/lib-track/CMakeLists.txt
  libraries/lib-track/PendingTracks.cpp
  libraries/lib-track/PendingTracks.h
  libraries/lib-track/Track.cpp
  libraries/lib-track/Track.h
  libraries/lib-track/UndoTracks.cpp
  libraries/lib-track/UndoTracks.h
  src/AudacityApp.cpp
  src/HistoryWindow.cpp
  src/MixerBoard.cpp
  src/Printing.cpp
  src/ProjectAudioManager.cpp
  src/ProjectFileManager.cpp
  src/ProjectWindow.cpp
  src/RealtimeEffectPanel.cpp
  src/TrackArtist.h
  src/TrackPanel.cpp
  src/tracks/labeltrack/ui/LabelTrackView.cpp
  src/tracks/playabletrack/notetrack/ui/NoteTrackAffordanceControls.cpp
  src/tracks/playabletrack/notetrack/ui/NoteTrackView.cpp
  src/tracks/playabletrack/wavetrack/ui/SpectrumView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveTrackAffordanceControls.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveformView.cpp
  src/tracks/timetrack/ui/TimeTrackView.cpp
  src/tracks/ui/ChannelView.cpp
  src/tracks/ui/CommonChannelView.cpp
  src/tracks/ui/TrackButtonHandles.cpp
Labels: Clips, refactoring

#5592 Make debug rebuilds on Mac a LOT faster...
  cmake-proxies/cmake-modules/AudacityFunctions.cmake
  scripts/build/macOS/fix_bundle.py
Labels: Build / CI

#4399 More in lib track selection
  libraries/lib-track-selection/CMakeLists.txt
  libraries/lib-track-selection/TrackFocus.cpp
  libraries/lib-track-selection/TrackFocus.h
  src/ProjectAudioManager.cpp
  src/ProjectFileManager.cpp
  src/ProjectWindow.cpp
  src/RealtimeEffectPanel.cpp
  src/SelectUtilities.cpp
  src/TrackPanel.cpp
  src/TrackPanelAx.cpp
  src/TrackPanelAx.h
  src/TrackUtilities.cpp
  src/commands/GetInfoCommand.cpp
  src/commands/SetTrackInfoCommand.cpp
  src/effects/EffectUI.cpp
  src/menus/ClipMenus.cpp
  src/menus/EditMenus.cpp
  src/menus/LabelMenus.cpp
  src/menus/NavigationMenus.cpp
  src/menus/PluginMenus.cpp
  src/menus/TrackMenus.cpp
  src/menus/TransportMenus.cpp
  src/toolbars/TranscriptionToolBar.cpp
  src/tracks/labeltrack/ui/LabelTrackView.cpp
  src/tracks/playabletrack/notetrack/ui/NoteTrackSliderHandles.cpp
  src/tracks/playabletrack/ui/PlayableTrackButtonHandles.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveChannelView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveTrackAffordanceControls.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveTrackControls.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveTrackMenuItems.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveTrackSliderHandles.cpp
  src/tracks/timetrack/ui/TimeTrackMenuItems.cpp
  src/tracks/ui/BrushHandle.cpp
  src/tracks/ui/EditCursorOverlay.cpp
  src/tracks/ui/SelectHandle.cpp
  src/tracks/ui/TrackButtonHandles.cpp
Labels: refactoring, dependency breaking, libraries & modules

#4364 Extract lib note track
  cmake-proxies/CMakeLists.txt
  cmake-proxies/portsmf/CMakeLists.txt
  libraries/CMakeLists.txt
  libraries/lib-note-track/CMakeLists.txt
  libraries/lib-note-track/MIDIPlay.cpp
  libraries/lib-note-track/MIDIPlay.h
  libraries/lib-note-track/NoteTrack.cpp
  libraries/lib-note-track/NoteTrack.h
  libraries/lib-note-track/WrapAllegro.h
  libraries/lib-registries/ClientData.cpp
  libraries/lib-registries/ClientData.h
  libraries/lib-registries/ClientDataHelpers.h
  libraries/lib-utility/CMakeLists.txt
  libraries/lib-utility/CRTPBase.h
  src/CMakeLists.txt
  src/commands/GetInfoCommand.cpp
  src/effects/ScoreAlignDialog.cpp
  src/effects/SoundTouchEffect.cpp
  src/effects/nyquist/Nyquist.cpp
  src/export/ExportMIDI.cpp
  src/import/ImportMIDI.cpp
  src/menus/EditMenus.cpp
  src/prefs/ImportExportPrefs.cpp
  src/prefs/ImportExportPrefs.h
  src/prefs/SpectrogramSettings.h
  src/prefs/WaveformSettings.h
  src/tracks/playabletrack/notetrack/ui/NoteTrackAffordanceControls.cpp
  src/tracks/playabletrack/notetrack/ui/NoteTrackButtonHandle.cpp
  src/tracks/playabletrack/notetrack/ui/NoteTrackControls.cpp
  src/tracks/playabletrack/notetrack/ui/NoteTrackDisplayData.cpp
  src/tracks/playabletrack/notetrack/ui/NoteTrackDisplayData.h
  src/tracks/playabletrack/notetrack/ui/NoteTrackShifter.cpp
  src/tracks/playabletrack/notetrack/ui/NoteTrackSliderHandles.cpp
  src/tracks/playabletrack/notetrack/ui/NoteTrackVRulerControls.cpp
  src/tracks/playabletrack/notetrack/ui/NoteTrackVZoomHandle.cpp
  src/tracks/playabletrack/notetrack/ui/NoteTrackView.cpp
  src/tracks/playabletrack/notetrack/ui/NoteTrackView.h
  src/tracks/playabletrack/notetrack/ui/StretchHandle.cpp
  src/tracks/ui/SelectHandle.cpp
Labels: MIDI, refactoring, libraries & modules

#5681 Fix bug in Noise Gate
  plug-ins/noisegate.ny
Labels: bug

#5662 Extract mod midi import export
  libraries/lib-files/FileNames.cpp
  libraries/lib-files/FileNames.h
  libraries/lib-import-export/Import.cpp
  libraries/lib-import-export/Import.h
  libraries/lib-module-manager/ModuleSettings.cpp
  modules/CMakeLists.txt
  modules/mod-lof/ImportLOF.cpp
  modules/mod-midi-import-export/CMakeLists.txt
  modules/mod-midi-import-export/ExportMIDI.cpp
  modules/mod-midi-import-export/ImportMIDI.cpp
  src/CMakeLists.txt
  src/DropTarget.cpp
  src/LabelTrack.cpp
  src/ProjectFileManager.cpp
  src/ProjectManager.cpp
  src/commands/OpenSaveCommands.cpp
  src/import/ImportMIDI.h
  src/prefs/ImportExportPrefs.cpp
  src/prefs/ImportExportPrefs.h
  src/prefs/PrefsPanel.cpp
  src/tracks/playabletrack/notetrack/ui/NoteTrackDisplayData.h
Labels: MIDI, refactoring, dependency breaking, libraries & modules

#5695 Fix assertion violation in Viewport when resizing a stereo track
  src/TrackPanel.cpp
Labels: bug

#5692 Some easy channel iteration rewrites
  libraries/lib-channel/Channel.cpp
  libraries/lib-snapping/Snap.cpp
  libraries/lib-wave-track/WaveClip.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  libraries/lib-wave-track/WaveTrackUtilities.cpp
  libraries/lib-wave-track/WaveTrackUtilities.h
  src/ProjectFileManager.cpp
  src/commands/SetClipCommand.cpp
  src/menus/EditMenus.cpp
  src/menus/TransportMenus.cpp
  src/tracks/playabletrack/wavetrack/ui/CutlineHandle.cpp
  src/tracks/playabletrack/wavetrack/ui/SpectrumView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveClipAdjustBorderHandle.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveTrackAffordanceControls.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveTrackControls.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveformView.cpp
  src/tracks/ui/TimeShiftHandle.cpp
Labels: Clips, refactoring
