Repository audacity/audacity, pull requests merged in 2024-05, with the labels that each got.

#6363 Play Meter remains just right of AudioSetup when maximizing window
  src/toolbars/ToolManager.cpp
Labels: Design Debt

#5642 Two modules independent of audacity
  libraries/CMakeLists.txt
  libraries/lib-preference-pages/CMakeLists.txt
  libraries/lib-preference-pages/LibraryPrefs.cpp
  libraries/lib-preference-pages/LibraryPrefs.h
  libraries/lib-preference-pages/PrefsPanel.cpp
  libraries/lib-preference-pages/PrefsPanel.h
  modules/import-export/mod-ffmpeg/CMakeLists.txt
  modules/import-export/mod-ffmpeg/FFmpegPrefs.cpp
  modules/import-export/mod-ffmpeg/lib-ffmpeg-support/CMakeLists.txt
  modules/import-export/mod-mp3/CMakeLists.txt
  modules/import-export/mod-mp3/ExportMP3.cpp
  modules/import-export/mod-mp3/MP3Prefs.cpp
  modules/sharing/mod-cloud-audiocom/ui/AudioComPrefsPanel.cpp
  src/CMakeLists.txt
Labels: refactoring, dependency breaking, libraries & modules

#6480 6479 near lossless graph
  libraries/lib-dynamic-range-processor/DynamicRangeProcessorHistory.cpp
  libraries/lib-dynamic-range-processor/DynamicRangeProcessorHistory.h
  libraries/lib-dynamic-range-processor/DynamicRangeProcessorTypes.h
  libraries/lib-utility/CMakeLists.txt
  libraries/lib-utility/LockFreeQueue.h
  src/CMakeLists.txt
  src/effects/Compressor.cpp
  src/effects/Compressor.h
  src/effects/CompressorEditor.cpp
  src/effects/CompressorEditor.h
  src/effects/CompressorInstance.cpp
  src/effects/CompressorInstance.h
  src/effects/DynamicRangeProcessorDummyOutputs.h
  src/effects/DynamicRangeProcessorEditor.cpp
  src/effects/DynamicRangeProcessorEditor.h
  src/effects/DynamicRangeProcessorEffectUtils.cpp
  src/effects/DynamicRangeProcessorEffectUtils.h
  src/effects/DynamicRangeProcessorHistoryPanel.cpp
  src/effects/DynamicRangeProcessorHistoryPanel.h
  src/effects/DynamicRangeProcessorOutputs.cpp
  src/effects/DynamicRangeProcessorOutputs.h
  src/effects/Limiter.cpp
  src/effects/LimiterEditor.cpp
  src/effects/LimiterEditor.h
  src/widgets/MeterPanel.cpp
  src/widgets/MeterPanel.h
Labels: Music

#6500 bugfix: scroll-to-track after import is complete
  src/DropTarget.cpp
  src/ProjectFileManager.cpp
  src/ProjectFileManager.h
  src/menus/EditMenus.cpp
  src/menus/FileMenus.cpp
Labels: bug
