Repository audacity/audacity, pull requests merged in 2024-03, with the labels that each got.

#6099 Adds OnIdle handler
  libraries/lib-utility/AppEvents.cpp
  libraries/lib-utility/AppEvents.h
  src/AudacityApp.cpp
Labels: 3.5

#6089 Wave clip invariants
  libraries/lib-audio-io/AudioIO.cpp
  libraries/lib-mixer/AudioIOSequences.h
  libraries/lib-wave-track/Sequence.cpp
  libraries/lib-wave-track/Sequence.h
  libraries/lib-wave-track/WaveClip.cpp
  libraries/lib-wave-track/WaveClip.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  modules/mod-aup/ImportAUP.cpp
Labels: Clips, refactoring

#6056 fix erroneous not-enough-space error
  src/tracks/playabletrack/wavetrack/ui/PitchAndSpeedDialog.cpp
Labels: Music, 3.5

#6146 Pitch shift display fixes
  src/tracks/playabletrack/wavetrack/ui/ClipOverflowButtonHandle.cpp
  src/tracks/playabletrack/wavetrack/ui/ClipPitchAndSpeedButtonHandle.cpp
  src/tracks/playabletrack/wavetrack/ui/LowlitClipButton.cpp
  src/tracks/playabletrack/wavetrack/ui/LowlitClipButton.h
Labels: 3.5

#6131 5981 non modal pitch and speed dialog
  libraries/lib-audio-io/AudioIO.cpp
  libraries/lib-shuttlegui/ShuttleGui.cpp
  libraries/lib-shuttlegui/ShuttleGui.h
  libraries/lib-viewport/Viewport.cpp
  libraries/lib-wave-track/WaveClip.cpp
  libraries/lib-wave-track/WaveClip.h
  libraries/lib-wave-track/WaveTrackUtilities.cpp
  libraries/lib-wave-track/WaveTrackUtilities.h
  src/CMakeLists.txt
  src/ProjectManager.cpp
  src/tracks/playabletrack/wavetrack/ui/ClipPitchAndSpeedButtonHandle.cpp
  src/tracks/playabletrack/wavetrack/ui/PitchAndSpeedDialog.cpp
  src/tracks/playabletrack/wavetrack/ui/PitchAndSpeedDialog.h
  src/tracks/playabletrack/wavetrack/ui/ShuttleGuiScopedSizer.h
  src/tracks/playabletrack/wavetrack/ui/WaveChannelView.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveClipUtilities.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveClipUtilities.h
  src/tracks/playabletrack/wavetrack/ui/WaveTrackAffordanceControls.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveTrackAffordanceHandle.cpp
  src/tracks/ui/SelectHandle.cpp
  src/widgets/MeterPanel.cpp
Labels: 3.5
