Repository audacity/audacity, pull requests merged in 2024-02, with the labels that each got.

#5919 Account for pitch ratio when evaluating time-and-pitch delay
  libraries/lib-time-and-pitch/StaffPadTimeAndPitch.cpp
  libraries/lib-time-and-pitch/StaffPadTimeAndPitch.h
Labels: Music

#5653 Wave color nonsense
  libraries/lib-effects/MixAndRender.h
  libraries/lib-stretching-sequence/tests/TestWaveClipMaker.cpp
  libraries/lib-stretching-sequence/tests/TestWaveClipMaker.h
  libraries/lib-wave-track/WaveClip.cpp
  libraries/lib-wave-track/WaveClip.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  libraries/lib-wave-track/WaveTrackUtilities.cpp
  src/CMakeLists.txt
  src/ProjectAudioManager.cpp
  src/commands/GetInfoCommand.cpp
  src/commands/SetClipCommand.cpp
  src/commands/SetTrackInfoCommand.cpp
  src/menus/TrackMenus.cpp
  src/tracks/playabletrack/wavetrack/ui/SpectrumCache.cpp
  src/tracks/playabletrack/wavetrack/ui/SpectrumCache.h
  src/tracks/playabletrack/wavetrack/ui/WaveformAppearance.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveformAppearance.h
  src/tracks/playabletrack/wavetrack/ui/WaveformCache.cpp
  src/tracks/playabletrack/wavetrack/ui/WaveformCache.h
  src/tracks/playabletrack/wavetrack/ui/WaveformView.cpp
Labels: Clips, refactoring

#5979 Use aligned vector in GetNormalizedCircularAutocorr, too.
  libraries/lib-music-information-retrieval/MirDsp.cpp
  libraries/lib-music-information-retrieval/MirDsp.h
Labels: Music

#6020 Fix assertion violation in Benchmark tool
  src/Benchmark.cpp
Labels: bug
