Repository audacity/audacity, pull requests merged in 2024-01, with the labels that each got.

#5835 Fix pasting of a multiple-clip cut into a new track, without overlap
  libraries/lib-wave-track/WaveTrack.cpp
Labels: bug, Clips, refactoring

#5752 Rewrite clear and paste
  libraries/lib-wave-track/WaveClip.cpp
  libraries/lib-wave-track/WaveClip.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
Labels: Clips, refactoring

#5765 Yet more easy channel iteration rewrites
  libraries/lib-wave-track/WaveClip.h
  libraries/lib-wave-track/WaveTrack.cpp
  libraries/lib-wave-track/WaveTrack.h
  src/ProjectAudioManager.cpp
Labels: Clips, refactoring

#5857 Attempt to fix Linux package build
  libraries/lib-wx-wrappers/AudacityDontAskAgainMessageDialog.h
Labels: Music

#5859 Tempo detection: cache miss minimization
  src/ClipMirAudioReader.cpp
  src/ClipMirAudioReader.h
Labels: Music

#5850 Fix undo/redo when import quietly stretches clip or changes tempo/t.s.
  src/ProjectFileManager.cpp
Labels: bug

#5839 5546 audio file header search for loop metadata
  cmake-proxies/cmake-modules/AudacityFunctions.cmake
  libraries/lib-file-formats/AcidizerTags.h
  libraries/lib-file-formats/CMakeLists.txt
  libraries/lib-import-export/AcidizerTagSerialization.cpp
  libraries/lib-import-export/AcidizerTagSerialization.h
  libraries/lib-import-export/CMakeLists.txt
  libraries/lib-import-export/GetAcidizerTags.cpp
  libraries/lib-import-export/GetAcidizerTags.h
  libraries/lib-import-export/LibsndfileTagger.cpp
  libraries/lib-import-export/LibsndfileTagger.h
  libraries/lib-import-export/riff-test-util/CMakeLists.txt
  libraries/lib-import-export/riff-test-util/RiffTestUtil.cpp
  libraries/lib-import-export/tests/AcidizerTagSerializationTests.cpp
  libraries/lib-import-export/tests/CMakeLists.txt
  libraries/lib-import-export/tests/GetAcidizerTagsTests.cpp
  libraries/lib-music-information-retrieval/CMakeLists.txt
  libraries/lib-music-information-retrieval/MirAudioReader.cpp
  libraries/lib-music-information-retrieval/MirAudioReader.h
  libraries/lib-music-information-retrieval/MusicInformationRetrieval.cpp
  libraries/lib-music-information-retrieval/MusicInformationRetrieval.h
  libraries/lib-music-information-retrieval/tests/MusicInformationRetrievalTests.cpp
  libraries/lib-tags/CMakeLists.txt
  libraries/lib-tags/Tags.h
  modules/mod-pcm/ImportPCM.cpp
  src/CMakeLists.txt
  src/ProjectFileManager.cpp
Labels: Music

#5867 5794 tempo detection speed improvement
  cmake-proxies/CMakeLists.txt
  cmake-proxies/pffft/CMakeLists.txt
  lib-src/pffft/README.txt
  lib-src/pffft/pffft.c
  lib-src/pffft/pffft.h
  lib-src/pffft/pfsimd_macros.h
  libraries/lib-music-information-retrieval/CMakeLists.txt
  libraries/lib-music-information-retrieval/DecimatingMirAudioReader.cpp
  libraries/lib-music-information-retrieval/DecimatingMirAudioReader.h
  libraries/lib-music-information-retrieval/MirAudioReader.h
  libraries/lib-music-information-retrieval/MirDsp.cpp
  libraries/lib-music-information-retrieval/MusicInformationRetrieval.cpp
  libraries/lib-music-information-retrieval/PowerSpectrumGetter.cpp
  libraries/lib-music-information-retrieval/PowerSpectrumGetter.h
  libraries/lib-music-information-retrieval/tests/MirAudioReaders.h
  libraries/lib-music-information-retrieval/tests/StftFrameProviderTests.cpp
  libraries/lib-music-information-retrieval/tests/TatumQuantizationFitBenchmarking.cpp
  libraries/lib-music-information-retrieval/tests/WavMirAudioReader.cpp
  libraries/lib-music-information-retrieval/tests/WavMirAudioReader.h
  libraries/lib-time-and-pitch/CMakeLists.txt
  libraries/lib-time-and-pitch/StaffPad/FourierTransform_pffft.cpp
  src/ClipMirAudioReader.cpp
  src/ClipMirAudioReader.h
Labels: Music

#5879 Fix for undesired merging of loops
  libraries/lib-wave-track/WaveClip.cpp
Labels: bug, Music, 3.5
