Repository audacity/audacity, pull requests merged in 2024-04, with the labels that each got.

#6214 One less arc in dependency graph...
  libraries/lib-cloud-audiocom/CMakeLists.txt
Labels: libraries & modules

#6345 Issue 6340: wrong vertical scroll recording to new track...
  src/ProjectAudioManager.cpp
Labels: bug

#6023 perf: optimize code to avoid executing if(i < 0) and while (1) in one loop cycle.
  libraries/lib-mixer/Envelope.cpp
Labels: performance
